version: '2.2'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile-develop
    image: backend:dev
    container_name: myexpenses_api
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app:/home/nodejs/app
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/my-expenses
    user: nodejs
  db:
    image: mongo:latest
    container_name: myexpenses_db
    ports:
     - "27017:27017"
